#!/usr/bin/env python3
"""Fail when public files contain unwanted contributor or tool attribution markers."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKIP_PARTS = {".git", "__pycache__", "node_modules"}
SKIP_SUFFIXES = {".pyc", ".tgz"}
PATTERNS = [
    re.compile(pattern, re.I)
    for pattern in [
        r"co-authored",
        r"coauthor",
        r"co-author",
        r"\bai assistant\b",
        r"generated by",
        r"(?:generated|written|created|co-authored) by .*?(?:claude|codex|anthropic|assistant)",
    ]
]


def should_skip(path: Path) -> bool:
    return bool(SKIP_PARTS.intersection(path.parts)) or path.suffix in SKIP_SUFFIXES


def scan(root: Path) -> list[str]:
    hits: list[str] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or should_skip(path.relative_to(root)):
            continue
        if path.name in {"attribution_scan.py", "Test-Attribution.ps1"}:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for line_number, line in enumerate(text.splitlines(), start=1):
            if any(pattern.search(line) for pattern in PATTERNS):
                hits.append(f"{path.relative_to(root)}:{line_number}: {line.strip()}")
    return hits


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=str(ROOT))
    args = parser.parse_args()
    hits = scan(Path(args.root))
    if hits:
        print("Attribution markers found:")
        for hit in hits:
            print(f"- {hit}")
        return 1
    print("Attribution scan passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
