# Test-Attribution.ps1 - Fail when public files contain unwanted contributor or
# tool attribution markers. Port of attribution_scan.py.

. "$PSScriptRoot/SlopBeth.Common.ps1"

$AttributionRoot = Split-Path $PSScriptRoot -Parent
$AttributionSkipParts = [System.Collections.Generic.HashSet[string]]::new([string[]]@('.git', '__pycache__', 'node_modules'), [System.StringComparer]::Ordinal)
$AttributionSkipSuffixes = [System.Collections.Generic.HashSet[string]]::new([string[]]@('.pyc', '.tgz'), [System.StringComparer]::OrdinalIgnoreCase)
# Scanner files define the marker phrases as literals; skip them (this script
# and the Python attribution scanner it ships alongside).
$AttributionSkipNames = [System.Collections.Generic.HashSet[string]]::new([string[]]@('Test-Attribution.ps1', 'attribution_scan.py'), [System.StringComparer]::OrdinalIgnoreCase)
$AttributionPatterns = @(
    [regex]::new('co-authored', 'IgnoreCase'),
    [regex]::new('coauthor', 'IgnoreCase'),
    [regex]::new('co-author', 'IgnoreCase'),
    [regex]::new('\bai assistant\b', 'IgnoreCase'),
    [regex]::new('generated by', 'IgnoreCase'),
    [regex]::new('(?:generated|written|created|co-authored) by .*?(?:claude|codex|anthropic|assistant)', 'IgnoreCase')
)
$AttributionThrowingUtf8 = [System.Text.UTF8Encoding]::new($false, $true)

function Test-AttributionSkip {
    param([string]$RelativePath)
    foreach ($part in ($RelativePath -split '[\\/]')) { if ($AttributionSkipParts.Contains($part)) { return $true } }
    return $AttributionSkipSuffixes.Contains([System.IO.Path]::GetExtension($RelativePath))
}

function Get-AttributionHits {
    param([string]$Root)
    $hits = [System.Collections.Generic.List[string]]::new()
    $files = @(Get-ChildItem -LiteralPath $Root -Recurse -File -Force | Sort-Object FullName)
    foreach ($file in $files) {
        $relative = $file.FullName.Substring($Root.Length).TrimStart('\', '/')
        if (Test-AttributionSkip $relative) { continue }
        if ($AttributionSkipNames.Contains($file.Name)) { continue }
        try { $text = [System.IO.File]::ReadAllText($file.FullName, $AttributionThrowingUtf8) }
        catch { continue }
        $lineNumber = 0
        foreach ($line in ($text -split "`n")) {
            $lineNumber++
            $line = $line -replace "`r$", ''
            foreach ($pattern in $AttributionPatterns) {
                if ($pattern.IsMatch($line)) { $hits.Add("${relative}:${lineNumber}: $($line.Trim())"); break }
            }
        }
    }
    return @($hits.ToArray())
}

function Invoke-TestAttributionCli {
    param([string[]]$Argv)
    $opts = ConvertFrom-CliArgs -Argv $Argv -Options @{ root = 'value' }
    $root = if ($opts['root']) { $opts['root'] } else { $AttributionRoot }
    $hits = @(Get-AttributionHits $root)
    if ($hits.Count) {
        [Console]::Out.WriteLine('Attribution markers found:')
        foreach ($hit in $hits) { [Console]::Out.WriteLine("- $hit") }
        exit 1
    }
    [Console]::Out.WriteLine('Attribution scan passed.')
    exit 0
}

if ($MyInvocation.InvocationName -ne '.') {
    Invoke-TestAttributionCli -Argv $args
}
